# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 449a2a8dbeae48d8c230d267da709c8e22e1408a23c99f9b209d64d21f60d9b63831631f8e60d5d4f2796c339deddef460533674625cb139f066cfa7740634db

test:
  secret_key_base: 9bcb2deea2f6c00b91b3de578c7d0ecfa9919e023c1959b42421571e8089cf37b02fe11278504091eb30a7d0802d66001846b08394bebca251673e25effa2ae2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
